/* SETTINGS */
export const SEARCH = "SEARCH";
export const SEARCH_BY = "SEARCH_BY";
export const SEARCH_KEYWORD = "SEARCH_KEYWORD";
export const GET_NOTIFICATION = "GET_NOTIFICATION";
/* COURSE */
export const GET_COURSE = "GET_COURSE";
export const GET_PENDING_COURSES = "GET_PENDING_COURSES";
export const COURSE_DELETED = "COURSE_DELETED";
export const COURSE_ACCEPTED = "COURSE_ACCEPTED";
export const GET_MY_COURSE = "GET_MY_COURSE";
export const GET_ACTIVE_COURSES = "GET_ACTIVE_COURSES";

/* COURSE */
export const GET_ROOMS = "GET_ROOMS";
export const GET_MY_ROOMS = "GET_MY_ROOMS";
export const ROOM_CREATED = "ROOM_CREATED";
export const ROOMS_ERROR = "ROOMS_ERROR";

export const ASSINGMENT_WITH_FILTER = "ASSINGMENT_WITH_FILTER";
export const GET_ASSIGNMENT_ERR = "GET_ASSIGNMENT_ERR";
export const GET_ASSIGNMENT = "GET_ASSIGNMENT";
/* AUTH */
export const ACCEPT_PROFILE = "ACCEPT_PROFILE";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const CONFIRMATION_USER = "CONFIRMATION_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const GET_PROFILE = "GET_PROFILE";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const GET_PROFILES = "GET_PROFILES";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const GET_REPORTS = "GET_REPORTS";
/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";

/* TODO APP*/

export const TODO_GET_LIST_SUCCESS = "TODO_GET_LIST_SUCCESS";
export const TODO_GET_LIST_ERROR = "TODO_GET_LIST_ERROR";
export const TODO_GET_LIST_WITH_FILTER = "TODO_GET_LIST_WITH_FILTER";
export const TODO_GET_LIST_WITH_ORDER = "TODO_GET_LIST_WITH_ORDER";

/* CHAT APP*/
export const CHAT_GET_CONTACTS = "CHAT_GET_CONTACTS";
export const CHAT_GET_CONTACTS_SUCCESS = "CHAT_GET_CONTACTS_SUCCESS";
export const CHAT_GET_CONTACTS_ERROR = "CHAT_GET_CONTACTS_ERROR";
export const CHAT_GET_CONVERSATIONS = "CHAT_GET_CONVERSATIONS";
export const CHAT_GET_CONVERSATIONS_SUCCESS = "CHAT_GET_CONVERSATIONS_SUCCESS";
export const CHAT_GET_CONVERSATIONS_ERROR = "CHAT_GET_CONVERSATIONS_ERROR";
export const CHAT_ADD_MESSAGE_TO_CONVERSATION =
  "CHAT_ADD_MESSAGE_TO_CONVERSATION";
export const CHAT_CREATE_CONVERSATION = "CHAT_CREATE_CONVERSATION";
export const CHAT_SEARCH_CONTACT = "CHAT_SEARCH_CONTACT";
export const CHAT_CHANGE_CONVERSATION = "CHAT_CHANGE_CONVERSATION";
export const CHAT_DELETE_CONVERSATION = "CHAT_DELETE_CONVERSATION";
/* SURVEY LIST APP*/

export const SAVE_QUIZ = "SAVE_QUIZ";
export const SURVEY_LIST_GET_LIST = "SURVEY_LIST_GET_LIST";
export const GET_QUIZ_LIST = "GET_QUIZ_LIST";
export const SURVEY_LIST_GET_LIST_ERROR = "SURVEY_LIST_GET_LIST_ERROR";
export const GET_QUIZ_LIST_WITH_FILTER = "GET_QUIZ_LIST_WITH_FILTER";
export const SURVEY_LIST_GET_LIST_WITH_ORDER =
  "SURVEY_LIST_GET_LIST_WITH_ORDER";
export const SURVEY_LIST_GET_LIST_SEARCH = "SURVEY_LIST_GET_LIST_SEARCH";
export const SURVEY_LIST_ADD_ITEM = "SURVEY_LIST_ADD_ITEM";
export const SURVEY_LIST_ADD_ITEM_SUCCESS = "SURVEY_LIST_ADD_ITEM_SUCCESS";
export const SURVEY_LIST_ADD_ITEM_ERROR = "SURVEY_LIST_ADD_ITEM_ERROR";
export const SURVEY_LIST_SELECTED_ITEMS_CHANGE =
  "SURVEY_LIST_SELECTED_ITEMS_CHANGE";

/* SURVEY DETAIL APP*/
export const GET_QUIZ_DETAIL = "GET_QUIZ_DETAIL";
export const SURVEY_GET_DETAILS_SUCCESS = "SURVEY_GET_DETAILS_SUCCESS";
export const GET_QUIZ_ERROR = "GET_QUIZ_ERROR";
export const SURVEY_DELETE_QUESTION = "SURVEY_DELETE_QUESTION";
export const SURVEY_SAVE = "SURVEY_SAVE";

/*Subscrier*/
export const GET_COURSE_SUBSCRIBERS = "GET_COURSE_SUBSCRIBERS";
export const GET_SUBSCRIBED_COURSES = "GET_SUBSCRIBED_COURSES";
export const GET_RECOMMENDED_COURSES = "GET_RECOMMENDED_COURSES";
export const GET_FOLLWERS = "GET_FOLLWERS";
export const GET_FOLLOWING = "GET_FOLLOWING";
export const GET_TOP_COURSES = "GET_TOP_COURSES";
export const GET_SIMILAR_COURSES = "GET_SIMILAR_COURSES";
